name: Resume CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build the Docker image with tag
      run: docker build . --file Dockerfile --tag ${{ secrets.ECR_REGISTRY }}/docker-resume-ecr:${{ github.run_number }}
      
    - name: Build the Docker image (latest)
      run: docker build . --file Dockerfile --tag ${{ secrets.ECR_REGISTRY }}/docker-resume-ecr:latest
      
    - name: Push the Docker image with version tag
      run: docker push ${{ secrets.ECR_REGISTRY }}/docker-resume-ecr:${{ github.run_number }}
      
    # - name: Push the Docker image with latest tag
    #   run: docker push ${{ secrets.ECR_REGISTRY }}/docker-resume-ecr:latest


    # steps:
    # - uses: actions/checkout@v4

    # - name: Build the Docker image with tag
    #   run: docker build . --file Dockerfile --tag my-image-name:${{ github.run_number }}
    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name
    
    # - name: Log in to Docker Hub
    #   run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
    
    # - name: Tag image
    #   run: docker tag my-image-name:${{ github.run_number }} ${{ secrets.REGISTRY_USERNAME }}/my-image-name:${{ github.run_number }}
    
    # - name: Push the Docker image with tag
    #   run: docker push ${{ secrets.REGISTRY_USERNAME }}/my-image-name:${{ github.run_number }}



  # deploy:
  
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Ssh to server
  #     uses: appleboy/ssh-action@v1.0.3
  #     with:
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USERNAME }}
  #       key: ${{ secrets.KEY }}
  #       port: 22
  #       script: |
  #         docker stop resume || echo ""
  #         docker rm resume || echo ""
  #         docker run -d --name resume -p 8080:5001 ${{ secrets.REGISTRY_USERNAME }}/docker-resume-ecr:${{ github.run_number }}
        
      
    

    